// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dmwaivyzfqdeyabenddk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRtd2Fpdnl6ZnFkZXlhYmVuZGRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNTIwMjUsImV4cCI6MjA2MDcyODAyNX0.Bu7iftsQF-HMnCbinY2v-70vdiA27cEk0OHyp4zODy0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);